#!/usr/bin/env python3

# Example from http://www.graphviz.org/content/siblings

siblings = Graph({'size': '36, 36', 'fontname': 'Arial', 'fontsize': 36, 'style': 'bold',
    'label': '\nKappa Kappa Psi/Tau Beta Sigma\nSan Diego State University\nEta Mu and Zeta Xi Family Tree\n\nto date: November 30th, 2008\n',
    'ssize': '30, 60'})
siblings.set_node_attr({'color': 'gray', 'style': 'filled', 'fontname': 'Verdana', 'size': '30, 30'})

siblings.add_edge('Michael Griffith', 'Lori Brede')
siblings.add_edge('Amie Holston', 'Lori Brede')
siblings.add_edge('Laura De\'Armond', 'Casey Carter')
siblings.add_edge('Chuk Gawlik', 'Japheth Cleaver')
siblings.add_edge('Stacy Snyder', 'Japheth Cleaver')
siblings.add_edge('David Guthrie', 'Jillian Clifton')
siblings.add_edge('Japheth Cleaver', 'Jillian Clifton')
siblings.add_edge('Tony Sacco', 'Laura De\'Armond')
siblings.add_edge('Heather Smith', 'Laura De\'Armond')
siblings.add_edge('Alex Hansen', 'Kevin Decker')
siblings.add_edge('Wanda Livelsberger', 'Kevin Decker')
siblings.add_edge('Alex Hansen', 'Patrick Doerr')
siblings.add_edge('Deanna Jagow', 'Patrick Doerr')
siblings.add_edge('Mark Pearson', 'Lori Asaro')
siblings.add_edge('Lori Ball', 'Lori Asaro')
siblings.add_edge('Rob Reiner', 'Ryan Farris')
siblings.add_edge('Cindy Teel', 'Ryan Farris')
siblings.add_edge('Mark Newton-John', 'Ginger Palmer')
siblings.add_edge('Mervin Maniago', 'Matthew FitzGerald')
siblings.add_edge('Amie Holston', 'Matthew FitzGerald')
siblings.add_edge('Mark Pearson', 'Tani Miller')
siblings.add_edge('Robert Walwick', 'Vienna McMurtry')
siblings.add_edge('Ginger Palmer', 'Vienna McMurtry')
siblings.add_edge('Kevin Decker', 'Chuck Foster')
siblings.add_edge('Karen Saye', 'Chuck Foster')
siblings.add_edge('Ginger Palmer', 'Gary Frampton')
siblings.add_edge('Sean Tipps', 'Pat Norris')
siblings.add_edge('Teresa Long', 'Pat Norris')
siblings.add_edge('Mark Pearson', 'Marc Martin-ez')
siblings.add_edge('Tani Miller', 'Marc Martin-ez')
siblings.add_edge('Kelly Erickson', 'Kristen Villone')
siblings.add_edge('Anna Pedroza', 'Kristen Villone')
siblings.add_edge('Chris Livelsberger', 'Geoff Frank')
siblings.add_edge('Amy Price', 'Geoff Frank')
siblings.add_edge('John FitzGibbon', 'Tracy Murray')
siblings.add_edge('Judy Dulcich', 'Tracy Murray')
siblings.add_edge('Robert Walwick', 'Ian McIntosh')
siblings.add_edge('Barbara Tollison', 'Ian McIntosh')
siblings.add_edge('Jayson Smith', 'Chuk Gawlik')
siblings.add_edge('Heather Smith', 'Chuk Gawlik')
siblings.add_edge('Mark Nadeau', 'Kelly McKinney')
siblings.add_edge('Judy Dulcich', 'Kelly McKinney')
siblings.add_edge('Chris Livelsberger', 'Deanna Jagow')
siblings.add_edge('Amy Price', 'Deanna Jagow')
siblings.add_edge('J. Angeles', 'Renee Thompson')
siblings.add_edge('Kelley Smith', 'Renee Thompson')
siblings.add_edge('John FitzGibbon', 'Steven Smith')
siblings.add_edge('Diane Reoch', 'Charlene Andrews')
siblings.add_edge('Gail Vasquez', 'Tonya Alexander')
siblings.add_edge('Becky Bernal', 'Spencer Caldwell')
siblings.add_edge('Chuk Gawlik', 'Michael Griffith')
siblings.add_edge('Wanda Livelsberger', 'Michael Griffith')
siblings.add_edge('Steven Smith', 'Russell Grant')
siblings.add_edge('Chuck Foster', 'David Guthrie')
siblings.add_edge('Tiffany Worthington', 'David Guthrie')
siblings.add_edge('John FitzGibbon', 'Jerry Maya')
siblings.add_edge('Russell Grant', 'Melissa Schwartz')
siblings.add_edge('Renee Thompson', 'Delphy Shaulis')
siblings.add_edge('Martin Naiman', 'Alex Hansen')
siblings.add_edge('Janean Angeles', 'Alex Hansen')
siblings.add_edge('Dennis McColl', 'Leslie Harlow')
siblings.add_edge('Denise Luna', 'Leslie Harlow')
siblings.add_edge('April Ortiz-cloninger', 'Jonathan Yudman')
siblings.add_edge('Spencer Caldwell', 'Michael Elgo')
siblings.add_edge('Carol Kropp', 'Michael Elgo')
siblings.add_edge('Marc Martin-ez', 'Denmark Vea')
siblings.add_edge('Kelley Smith', 'Denmark Vea')
siblings.add_edge('Martin Naiman', 'Kathleen Hansen')
siblings.add_edge('Heather Smith', 'Kathleen Hansen')
siblings.add_edge('April Ortiz-cloninger', 'Laura Stegner')
siblings.add_edge('J. Angeles', 'Kathy Jones')
siblings.add_edge('Erick Sugimura', 'Eric Gates')
siblings.add_edge('Laura Stegner', 'Eric Gates')
siblings.add_edge('Eric Gates', 'Jennifer Stoewe')
siblings.add_edge('Kevin Decker', 'Karen Helbling')
siblings.add_edge('Regan Ashker', 'Karen Helbling')
siblings.add_edge('Eric Gates', 'Scott Wood')
siblings.add_edge('Greg Flood', 'J. Angeles')
siblings.add_edge('Ginger Palmer', 'J. Angeles')
siblings.add_edge('Chuk Gawlik', 'Amie Holston')
siblings.add_edge('Lynn Reeves', 'Amie Holston')
siblings.add_edge('Michael Elgo', 'Susan Colwell')
siblings.add_edge('Kevin Owens', 'Christopher Jouan')
siblings.add_edge('Michael Elgo', 'Kristianna Reynante')
siblings.add_edge('Janean Angeles', 'Kristianna Reynante')
siblings.add_edge('Amy Berner', 'Stacy Snyder')
siblings.add_edge('Alex Hansen', 'Deanna Johnson')
siblings.add_edge('Laura De\'Armond', 'Deanna Johnson')
siblings.add_edge('Russell Grant', 'Johnny Richardson')
siblings.add_edge('James Rowland', 'Nathan Fellhauer')
siblings.add_edge('Kristianna Reynante', 'Nathan Fellhauer')
siblings.add_edge('Sean McHenry', 'Brian Raneses')
siblings.add_edge('Martin Naiman', 'Penny Lewis')
siblings.add_edge('Kristen Elgo', 'Becky Graham')
siblings.add_edge('Rob Reiner', 'Steven Gross')
siblings.add_edge('Stacy Snyder', 'Steven Gross')
siblings.add_edge('Mark Newton-John', 'Sedona Reynolds')
siblings.add_edge('Cindy Teel', 'Sedona Reynolds')
siblings.add_edge('Nathan Fellhauer', 'Klair Mayerchak')
siblings.add_edge('Becky Graham', 'Klair Mayerchak')
siblings.add_edge('Sean McHenry', 'Shari VerBerkmoes')
siblings.add_edge('Janean Angeles', 'Shari VerBerkmoes')
siblings.add_edge('James Rowland', 'Anson Summers')
siblings.add_edge('Rob Reiner', 'Dusty Jolliff')
siblings.add_edge('Stacy Snyder', 'Dusty Jolliff')
siblings.add_edge('James Rowland', 'Jennifer Garman')
siblings.add_edge('Rob Reiner', 'Kelly Greenhill')
siblings.add_edge('Kristen Elgo', 'Kelly Greenhill')
siblings.add_edge('J. Angeles', 'Lucinda Farless')
siblings.add_edge('Susan Colwell', 'Lucinda Farless')
siblings.add_edge('Chuk Gawlik', 'Alfredo Cardenas')
siblings.add_edge('Kathleen Hansen', 'Alfredo Cardenas')
siblings.add_edge('Andrea Owens', 'Jennifer Jouan')
siblings.add_edge('Joseph Butler', 'Tamara Scrivner')
siblings.add_edge('Sarah Maltese', 'Tamara Scrivner')
siblings.add_edge('Ryan Underwood', 'Bradley Stouse')
siblings.add_edge('Cindy Teel', 'Bradley Stouse')
siblings.add_edge('Kristopher Lininger', 'Casondra Brimmage')
siblings.add_edge('Ilana Melcher', 'Casondra Brimmage')
siblings.add_edge('Jeremy Frazier', 'Cassiopeia Guthrie')
siblings.add_edge('Christine Mount', 'Cassiopeia Guthrie')
siblings.add_edge('Matthew FitzGerald', 'Kathleen Moran')
siblings.add_edge('Lori Brede', 'Kathleen Moran')
siblings.add_edge('Tony Sacco', 'Tiffany Kalland')
siblings.add_edge('Karen Helbling', 'Tiffany Kalland')
siblings.add_edge('David Guthrie', 'Kristen Anderson')
siblings.add_edge('Jennie Bogart', 'Kristen Anderson')
siblings.add_edge('Jon Weisel', 'Laura Simonette')
siblings.add_edge('Japheth Cleaver', 'Laura Simonette')
siblings.add_edge('David Guthrie', 'Nathan Williams')
siblings.add_edge('Karen Helbling', 'Nathan Williams')
siblings.add_edge('Ryan Underwood', 'Rebecca Hippert')
siblings.add_edge('Tiffany Kalland', 'Rebecca Hippert')
siblings.add_edge('Joseph Butler', 'Samuel Wallace')
siblings.add_edge('Deanna Jagow', 'Samuel Wallace')
siblings.add_edge('Jeremy Frazier', 'Scott Gardner')
siblings.add_edge('Christine Mount', 'Scott Gardner')
siblings.add_edge('Bradley Stouse', 'Alberto Ayon')
siblings.add_edge('Jennie Bogart', 'Alberto Ayon')
siblings.add_edge('Nathan Williams', 'Susannah Clayton')
siblings.add_edge('Karen Helbling', 'Susannah Clayton')
siblings.add_edge('Scott Gardner', 'Lisa Gochnauer')
siblings.add_edge('Casondra Brimmage', 'Lisa Gochnauer')
siblings.add_edge('Samuel Wallace', 'Jamie Jackson')
siblings.add_edge('Tamara Scrivner', 'Jamie Jackson')
siblings.add_edge('Matthew FitzGerald', 'Christina Kelly')
siblings.add_edge('Lori Brede', 'Christina Kelly')
siblings.add_edge('Mark Newton-John', 'Gara Thornton')
siblings.add_edge('Laura Simonette', 'Gara Thornton')
siblings.add_edge('Scott Gardner', 'Robert Winebarger')
siblings.add_edge('Robin Ellison', 'Robert Winebarger')
siblings.add_edge('Rob Reiner', 'Jeremy Kirchner')
siblings.add_edge('Jennifer Brandon', 'Sandy Konar')
siblings.add_edge('Rob Reiner', 'Dan Kuhlman')
siblings.add_edge('Dusty Jolliff', 'Dan Kuhlman')
siblings.add_edge('Martin Naiman', 'Lindsay Arehart')
siblings.add_edge('Jennifer Brandon', 'Lindsay Arehart')
siblings.add_edge('J. Angeles', 'Mervin Maniago')
siblings.add_edge('Kathy Jones', 'Mervin Maniago')
siblings.add_edge('Mark Newton-John', 'Jarrod Monroe')
siblings.add_edge('Jamie Fratacci', 'Jarrod Monroe')
siblings.add_edge('Chuk Gawlik', 'Jamie Fratacci')
siblings.add_edge('Tiffany Worthington', 'Jamie Fratacci')
siblings.add_edge('Russell Grant', 'Martin Naiman')
siblings.add_edge('Tonya Alexander', 'Martin Naiman')
siblings.add_edge('Edward Givens', 'Mark Newton-John')
siblings.add_edge('Regan Ashker', 'Veronica Nickel')
siblings.add_edge('Wanda Livelsberger', 'Lynn Reeves')
siblings.add_edge('Jayson Smith', 'Bryan Ransom')
siblings.add_edge('Tony Sacco', 'Regan Ashker')
siblings.add_edge('Dusty Jolliff', 'Regan Ashker')
siblings.add_edge('Matthew FitzGerald', 'Jennifer Stout')
siblings.add_edge('Deanna Jagow', 'Jennifer Stout')
siblings.add_edge('Sean McHenry', 'James Rowland')
siblings.add_edge('James Rowland', 'Wanda Livelsberger')
siblings.add_edge('Janean Angeles', 'Wanda Livelsberger')
siblings.add_edge('Mervin Maniago', 'Melissa Roy')
siblings.add_edge('Christina Kelly', 'Melissa Roy')
siblings.add_edge('Dennis McColl', 'Tony Sacco')
siblings.add_edge('April Ortiz-cloninger', 'Tony Sacco')
siblings.add_edge('Tony Sacco', 'Karen Saye')
siblings.add_edge('Tony Sacco', 'Amy Price')
siblings.add_edge('Kathleen Hansen', 'Amy Price')
siblings.add_edge('James Rowland', 'Jayson Smith')
siblings.add_edge('Brian Raneses', 'Heather Smith')
siblings.add_edge('Kristen Elgo', 'Heather Smith')
siblings.add_edge('David Guthrie', 'Josh Atwood')
siblings.add_edge('Lori Brede', 'Josh Atwood')
siblings.add_edge('Patrick Doerr', 'Katie Browne')
siblings.add_edge('Jamie Fratacci', 'Katie Browne')
siblings.add_edge('James Rowland', 'Kristin Tang')
siblings.add_edge('Heather Smith', 'Kristin Tang')
siblings.add_edge('Mervin Maniago', 'Cindy Teel')
siblings.add_edge('Veronica Nickel', 'Cindy Teel')
siblings.add_edge('Matthew FitzGerald', 'Mike Tulumello')
siblings.add_edge('Katie Browne', 'Mike Tulumello')
siblings.add_edge('Ryan Farris', 'Veronica Villanueva')
siblings.add_edge('Sedona Reynolds', 'Veronica Villanueva')
siblings.add_edge('Mervin Maniago', 'Tiffany Worthington')
siblings.add_edge('Jennifer Jouan', 'Tiffany Worthington')
siblings.add_edge('James Rowland', 'Scott Wright')
siblings.add_edge('Kristen Elgo', 'Scott Wright')
siblings.add_edge('Matthew FitzGerald', 'Jeremy Browne')
siblings.add_edge('Japheth Cleaver', 'Jeremy Browne')
siblings.add_edge('Alberto Ayon', 'James Fogelman')
siblings.add_edge('Susannah Clayton', 'James Fogelman')
siblings.add_edge('David Guthrie', 'Sandra Chase')
siblings.add_edge('Japheth Cleaver', 'Sandra Chase')
siblings.add_edge('Patrick Doerr', 'Joseph Butler')
siblings.add_edge('Deanna Jagow', 'Joseph Butler')
siblings.add_edge('Nathan Williams', 'Laura Fisher')
siblings.add_edge('Casondra Brimmage', 'Laura Fisher')
siblings.add_edge('Scott Wright', 'Katie Kozma')
siblings.add_edge('Robin Ellison', 'Katie Kozma')
siblings.add_edge('Joseph Butler', 'Rachel Perkins')
siblings.add_edge('Cassiopeia Guthrie', 'Rachel Perkins')
siblings.add_edge('Robert Winebarger', 'Sarah Titilah')
siblings.add_edge('Karen Helbling', 'Sarah Titilah')
siblings.add_edge('Laura Fisher', 'Ashley Rehart')
siblings.add_edge('Katie Kozma', 'Cara Yancey')
siblings.add_edge('Cara Yancey', 'Ashley Presley')
siblings.add_edge('Robin Ellison', 'Leila Wilhelm')
siblings.add_edge('Sean McHenry', 'Kristen Elgo')
siblings.add_edge('Stacy Snyder', 'Kristen Elgo')
siblings.add_edge('Ryan Farris', 'Greg Moody')
siblings.add_edge('Jennifer Stout', 'Greg Moody')
siblings.add_edge('Rachel Perkins', 'Lisa Fleck')
siblings.add_edge('Rachel Perkins', 'Christine Coyne')
siblings.add_edge('Laura Fisher', 'Jennifer Cooley')
siblings.add_edge('Ashley Rehart', 'Elizabeth Larios')
siblings.add_edge('Katie Kozma', 'Cate Threlkeld')
siblings.add_edge('Patrick Doerr', 'Erika Tapia')
siblings.add_edge('Melissa Roy', 'Erika Tapia')
siblings.add_edge('Jarrod Monroe', 'Robbyn Rozelle')
siblings.add_edge('Tiffany Kalland', 'Robbyn Rozelle')
siblings.add_edge('Ryan Farris', 'Ilana Melcher')
siblings.add_edge('Veronica Villanueva', 'Ilana Melcher')
siblings.add_edge('Greg Moody', 'Ryan Underwood')
siblings.add_edge('Katie Browne', 'Ryan Underwood')
siblings.add_edge('Joseph Butler', 'Cameron Brown')
siblings.add_edge('Tiffany Kalland', 'Cameron Brown')
siblings.add_edge('Ryan Underwood', 'Christine Mount')
siblings.add_edge('Lori Brede', 'Christine Mount')
siblings.add_edge('Greg Moody', 'Janay Rabe')
siblings.add_edge('Cindy Teel', 'Janay Rabe')
siblings.add_edge('Jeremy Browne', 'Jennie Bogart')
siblings.add_edge('Tiffany Kalland', 'Jennie Bogart')
siblings.add_edge('Ryan Farris', 'Jeremy Frazier')
siblings.add_edge('Ilana Melcher', 'Jeremy Frazier')
siblings.add_edge('Patrick Doerr', 'Crystal Bozak')
siblings.add_edge('Katie Browne', 'Crystal Bozak')
siblings.add_edge('Matthew FitzGerald', 'Kameka Smith')
siblings.add_edge('Ilana Melcher', 'Kameka Smith')
siblings.add_edge('Joseph Butler', 'Kyra Sacco')
siblings.add_edge('Robbyn Rozelle', 'Kyra Sacco')
siblings.add_edge('Ryan Underwood', 'Samuel Behar')
siblings.add_edge('Lori Brede', 'Samuel Behar')
siblings.add_edge('Patrick Doerr', 'Sarah Maltese')
siblings.add_edge('Deanna Jagow', 'Sarah Maltese')
siblings.add_edge('Tony Sacco', 'David Bronson')
siblings.add_edge('Kristin Alongi-Hutchins', 'David Bronson')
siblings.add_edge('Cameron Brown', 'Kristopher Lininger')
siblings.add_edge('Kameka Smith', 'Kristopher Lininger')
siblings.add_edge('Christine Coyne', 'Rakan Abu-Rahma')
siblings.add_edge('Jennifer Berry', 'Janean Angeles')
siblings.add_edge('Penny Lewis', 'Kristin Alongi-Hutchins')
siblings.add_edge('Greg Moody', 'Melissa Bebak')
siblings.add_edge('Sarah Maltese', 'Melissa Bebak')
siblings.add_edge('Scott Wright', 'Jennifer Brandon')
siblings.add_edge('Japheth Cleaver', 'Jennifer Brandon')
siblings.add_edge('Samuel Behar', 'Robin Ellison')
siblings.add_edge('Kyra Sacco', 'Robin Ellison')
siblings.add_edge('Joseph Butler', 'Teresa Simms')
siblings.add_edge('Janay Rabe', 'Teresa Simms')
siblings.add_edge('Robert Schmidtke', 'John FitzGibbon')
siblings.add_edge('Jean Newman', 'John FitzGibbon')
siblings.add_edge('Elizabeth Larios', 'Brittany DePew')
siblings.add_edge('Ashley Rehart', 'Kathleen Halberg')
siblings.add_edge('J. Angeles', 'Terrance Hirsch')
siblings.add_edge('Susan Colwell', 'Terrance Hirsch')
siblings.add_edge('Ashley Presley', 'Monique Arellano')
siblings.add_edge('Jennifer Cooley', 'Anthony Henderson')
siblings.add_edge('Cate Threlkeld', 'Amethyst Tagle')
siblings.add_edge('Lisa Fleck', 'Mallory Williams')

siblings.set_attr_for_nodes(['Lori Brede'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=10'})
siblings.set_attr_for_nodes(['Michael Griffith'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=24'})
siblings.set_attr_for_nodes(['Amie Holston'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=30'})
siblings.set_attr_for_nodes(['Casey Carter'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=11'})
siblings.set_attr_for_nodes(['Laura De\'Armond'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=14'})
siblings.set_attr_for_nodes(['Japheth Cleaver'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=12'})
siblings.set_attr_for_nodes(['Chuk Gawlik'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=22'})
siblings.set_attr_for_nodes(['Stacy Snyder'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=309'})
siblings.set_attr_for_nodes(['Jillian Clifton'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=13'})
siblings.set_attr_for_nodes(['David Guthrie'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=25'})
siblings.set_attr_for_nodes(['Tony Sacco'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=55'})
siblings.set_attr_for_nodes(['Heather Smith'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=59'})
siblings.set_attr_for_nodes(['Kevin Decker'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=15'})
siblings.set_attr_for_nodes(['Alex Hansen'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=26'})
siblings.set_attr_for_nodes(['Wanda Livelsberger'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=53'})
siblings.set_attr_for_nodes(['Patrick Doerr'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=16'})
siblings.set_attr_for_nodes(['Deanna Jagow'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=23'})
siblings.set_attr_for_nodes(['Lori Asaro'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=178'})
siblings.set_attr_for_nodes(['Mark Pearson'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=169'})
siblings.set_attr_for_nodes(['Lori Ball'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=167'})
siblings.set_attr_for_nodes(['Ryan Farris'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=18'})
siblings.set_attr_for_nodes(['Rob Reiner'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=51'})
siblings.set_attr_for_nodes(['Cindy Teel'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=62'})
siblings.set_attr_for_nodes(['Ginger Palmer'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=180'})
siblings.set_attr_for_nodes(['Mark Newton-John'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=46'})
siblings.set_attr_for_nodes(['Matthew FitzGerald'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=19'})
siblings.set_attr_for_nodes(['Mervin Maniago'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=41'})
siblings.set_attr_for_nodes(['Tani Miller'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=195'})
siblings.set_attr_for_nodes(['Vienna McMurtry'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=196'})
siblings.set_attr_for_nodes(['Robert Walwick'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=153'})
siblings.set_attr_for_nodes(['Chuck Foster'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=20'})
siblings.set_attr_for_nodes(['Karen Saye'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=56'})
siblings.set_attr_for_nodes(['Gary Frampton'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=201'})
siblings.set_attr_for_nodes(['Pat Norris'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=207'})
siblings.set_attr_for_nodes(['Sean Tipps'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=204'})
siblings.set_attr_for_nodes(['Teresa Long'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=194'})
siblings.set_attr_for_nodes(['Marc Martin-ez'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=208'})
siblings.set_attr_for_nodes(['Kristen Villone'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=209'})
siblings.set_attr_for_nodes(['Kelly Erickson'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=199'})
siblings.set_attr_for_nodes(['Anna Pedroza'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=197'})
siblings.set_attr_for_nodes(['Geoff Frank'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=21'})
siblings.set_attr_for_nodes(['Chris Livelsberger'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=40'})
siblings.set_attr_for_nodes(['Amy Price'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=57'})
siblings.set_attr_for_nodes(['Tracy Murray'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=210'})
siblings.set_attr_for_nodes(['John FitzGibbon'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=92'})
siblings.set_attr_for_nodes(['Judy Dulcich'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=177'})
siblings.set_attr_for_nodes(['Ian McIntosh'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=215'})
siblings.set_attr_for_nodes(['Barbara Tollison'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=172'})
siblings.set_attr_for_nodes(['Jayson Smith'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=58'})
siblings.set_attr_for_nodes(['Kelly McKinney'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=222'})
siblings.set_attr_for_nodes(['Mark Nadeau'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=183'})
siblings.set_attr_for_nodes(['Renee Thompson'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=231'})
siblings.set_attr_for_nodes(['J. Angeles'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=3'})
siblings.set_attr_for_nodes(['Kelley Smith'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=223'})
siblings.set_attr_for_nodes(['Steven Smith'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=233'})
siblings.set_attr_for_nodes(['Charlene Andrews'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=234'})
siblings.set_attr_for_nodes(['Diane Reoch'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=227'})
siblings.set_attr_for_nodes(['Tonya Alexander'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=238'})
siblings.set_attr_for_nodes(['Gail Vasquez'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=225'})
siblings.set_attr_for_nodes(['Spencer Caldwell'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=239'})
siblings.set_attr_for_nodes(['Becky Bernal'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=218'})
siblings.set_attr_for_nodes(['Russell Grant'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=242'})
siblings.set_attr_for_nodes(['Tiffany Worthington'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=66'})
siblings.set_attr_for_nodes(['Jerry Maya'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=250'})
siblings.set_attr_for_nodes(['Melissa Schwartz'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=252'})
siblings.set_attr_for_nodes(['Delphy Shaulis'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=255'})
siblings.set_attr_for_nodes(['Martin Naiman'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=45'})
siblings.set_attr_for_nodes(['Janean Angeles'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=86'})
siblings.set_attr_for_nodes(['Leslie Harlow'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=265'})
siblings.set_attr_for_nodes(['Dennis McColl'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=251'})
siblings.set_attr_for_nodes(['Denise Luna'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=236'})
siblings.set_attr_for_nodes(['Jonathan Yudman'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=267'})
siblings.set_attr_for_nodes(['April Ortiz-cloninger'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=258'})
siblings.set_attr_for_nodes(['Michael Elgo'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=268'})
siblings.set_attr_for_nodes(['Carol Kropp'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=254'})
siblings.set_attr_for_nodes(['Denmark Vea'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=269'})
siblings.set_attr_for_nodes(['Kathleen Hansen'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=27'})
siblings.set_attr_for_nodes(['Laura Stegner'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=274'})
siblings.set_attr_for_nodes(['Kathy Jones'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=28'})
siblings.set_attr_for_nodes(['Eric Gates'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=282'})
siblings.set_attr_for_nodes(['Erick Sugimura'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=280'})
siblings.set_attr_for_nodes(['Jennifer Stoewe'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=288'})
siblings.set_attr_for_nodes(['Karen Helbling'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=29'})
siblings.set_attr_for_nodes(['Regan Ashker'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=5'})
siblings.set_attr_for_nodes(['Scott Wood'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=295'})
siblings.set_attr_for_nodes(['Greg Flood'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=200'})
siblings.set_attr_for_nodes(['Lynn Reeves'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=48'})
siblings.set_attr_for_nodes(['Susan Colwell'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=302'})
siblings.set_attr_for_nodes(['Christopher Jouan'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=306'})
siblings.set_attr_for_nodes(['Kevin Owens'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=245'})
siblings.set_attr_for_nodes(['Kristianna Reynante'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=308'})
siblings.set_attr_for_nodes(['Amy Berner'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=300'})
siblings.set_attr_for_nodes(['Deanna Johnson'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=31'})
siblings.set_attr_for_nodes(['Johnny Richardson'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=310'})
siblings.set_attr_for_nodes(['Nathan Fellhauer'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=313'})
siblings.set_attr_for_nodes(['James Rowland'], {'color': 'thistle', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=52'})
siblings.set_attr_for_nodes(['Brian Raneses'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=314'})
siblings.set_attr_for_nodes(['Sean McHenry'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=42'})
siblings.set_attr_for_nodes(['Penny Lewis'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=315'})
siblings.set_attr_for_nodes(['Becky Graham'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=316'})
siblings.set_attr_for_nodes(['Kristen Elgo'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=7'})
siblings.set_attr_for_nodes(['Steven Gross'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=318'})
siblings.set_attr_for_nodes(['Sedona Reynolds'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=32'})
siblings.set_attr_for_nodes(['Klair Mayerchak'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=320'})
siblings.set_attr_for_nodes(['Shari VerBerkmoes'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=321'})
siblings.set_attr_for_nodes(['Anson Summers'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=326'})
siblings.set_attr_for_nodes(['Dusty Jolliff'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=33'})
siblings.set_attr_for_nodes(['Jennifer Garman'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=331'})
siblings.set_attr_for_nodes(['Kelly Greenhill'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=333'})
siblings.set_attr_for_nodes(['Lucinda Farless'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=334'})
siblings.set_attr_for_nodes(['Alfredo Cardenas'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=335'})
siblings.set_attr_for_nodes(['Jennifer Jouan'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=34'})
siblings.set_attr_for_nodes(['Andrea Owens'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=276'})
siblings.set_attr_for_nodes(['Tamara Scrivner'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=345'})
siblings.set_attr_for_nodes(['Joseph Butler'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=69'})
siblings.set_attr_for_nodes(['Sarah Maltese'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=83'})
siblings.set_attr_for_nodes(['Bradley Stouse'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=346'})
siblings.set_attr_for_nodes(['Ryan Underwood'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=74'})
siblings.set_attr_for_nodes(['Casondra Brimmage'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=347'})
siblings.set_attr_for_nodes(['Kristopher Lininger'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=85'})
siblings.set_attr_for_nodes(['Ilana Melcher'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=73'})
siblings.set_attr_for_nodes(['Cassiopeia Guthrie'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=348'})
siblings.set_attr_for_nodes(['Jeremy Frazier'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=79'})
siblings.set_attr_for_nodes(['Christine Mount'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=76'})
siblings.set_attr_for_nodes(['Kathleen Moran'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=349'})
siblings.set_attr_for_nodes(['Tiffany Kalland'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=35'})
siblings.set_attr_for_nodes(['Kristen Anderson'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=350'})
siblings.set_attr_for_nodes(['Jennie Bogart'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=78'})
siblings.set_attr_for_nodes(['Laura Simonette'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=351'})
siblings.set_attr_for_nodes(['Jon Weisel'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=89'})
siblings.set_attr_for_nodes(['Nathan Williams'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=352'})
siblings.set_attr_for_nodes(['Rebecca Hippert'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=353'})
siblings.set_attr_for_nodes(['Samuel Wallace'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=354'})
siblings.set_attr_for_nodes(['Scott Gardner'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=355'})
siblings.set_attr_for_nodes(['Alberto Ayon'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=356'})
siblings.set_attr_for_nodes(['Susannah Clayton'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=357'})
siblings.set_attr_for_nodes(['Lisa Gochnauer'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=358'})
siblings.set_attr_for_nodes(['Jamie Jackson'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=359'})
siblings.set_attr_for_nodes(['Christina Kelly'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=36'})
siblings.set_attr_for_nodes(['Gara Thornton'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=360'})
siblings.set_attr_for_nodes(['Robert Winebarger'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=361'})
siblings.set_attr_for_nodes(['Robin Ellison'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=90'})
siblings.set_attr_for_nodes(['Jeremy Kirchner'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=37'})
siblings.set_attr_for_nodes(['Sandy Konar'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=38'})
siblings.set_attr_for_nodes(['Jennifer Brandon'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=9'})
siblings.set_attr_for_nodes(['Dan Kuhlman'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=39'})
siblings.set_attr_for_nodes(['Lindsay Arehart'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=4'})
siblings.set_attr_for_nodes(['Jarrod Monroe'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=43'})
siblings.set_attr_for_nodes(['Jamie Fratacci'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=44'})
siblings.set_attr_for_nodes(['Veronica Nickel'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=47'})
siblings.set_attr_for_nodes(['Bryan Ransom'], {'color': 'thistle', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=49'})
siblings.set_attr_for_nodes(['Jennifer Stout'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=50'})
siblings.set_attr_for_nodes(['Melissa Roy'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=54'})
siblings.set_attr_for_nodes(['Josh Atwood'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=6'})
siblings.set_attr_for_nodes(['Katie Browne'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=60'})
siblings.set_attr_for_nodes(['Kristin Tang'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=61'})
siblings.set_attr_for_nodes(['Mike Tulumello'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=63'})
siblings.set_attr_for_nodes(['Veronica Villanueva'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=64'})
siblings.set_attr_for_nodes(['Scott Wright'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=67'})
siblings.set_attr_for_nodes(['Jeremy Browne'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=68'})
siblings.set_attr_for_nodes(['James Fogelman'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=688'})
siblings.set_attr_for_nodes(['Sandra Chase'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=689'})
siblings.set_attr_for_nodes(['Laura Fisher'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=690'})
siblings.set_attr_for_nodes(['Katie Kozma'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=691'})
siblings.set_attr_for_nodes(['Rachel Perkins'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=692'})
siblings.set_attr_for_nodes(['Sarah Titilah'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=693'})
siblings.set_attr_for_nodes(['Ashley Rehart'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=694'})
siblings.set_attr_for_nodes(['Cara Yancey'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=695'})
siblings.set_attr_for_nodes(['Ashley Presley'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=698'})
siblings.set_attr_for_nodes(['Leila Wilhelm'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=699'})
siblings.set_attr_for_nodes(['Greg Moody'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=70'})
siblings.set_attr_for_nodes(['Lisa Fleck'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=700'})
siblings.set_attr_for_nodes(['Christine Coyne'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=701'})
siblings.set_attr_for_nodes(['Jennifer Cooley'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=702'})
siblings.set_attr_for_nodes(['Elizabeth Larios'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=703'})
siblings.set_attr_for_nodes(['Cate Threlkeld'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=707'})
siblings.set_attr_for_nodes(['Erika Tapia'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=71'})
siblings.set_attr_for_nodes(['Robbyn Rozelle'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=72'})
siblings.set_attr_for_nodes(['Cameron Brown'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=75'})
siblings.set_attr_for_nodes(['Janay Rabe'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=77'})
siblings.set_attr_for_nodes(['Crystal Bozak'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=8'})
siblings.set_attr_for_nodes(['Kameka Smith'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=80'})
siblings.set_attr_for_nodes(['Kyra Sacco'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=81'})
siblings.set_attr_for_nodes(['Samuel Behar'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=82'})
siblings.set_attr_for_nodes(['David Bronson'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=84'})
siblings.set_attr_for_nodes(['Kristin Alongi-Hutchins'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=87'})
siblings.set_attr_for_nodes(['Rakan Abu-Rahma'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=852'})
siblings.set_attr_for_nodes(['Jennifer Berry'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=270'})
siblings.set_attr_for_nodes(['Melissa Bebak'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=88'})
siblings.set_attr_for_nodes(['Teresa Simms'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=91'})
siblings.set_attr_for_nodes(['Robert Schmidtke'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=188'})
siblings.set_attr_for_nodes(['Jean Newman'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=166'})
siblings.set_attr_for_nodes(['Brittany DePew'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=928'})
siblings.set_attr_for_nodes(['Kathleen Halberg'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=929'})
siblings.set_attr_for_nodes(['Terrance Hirsch'], {'color': 'lightblue', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=96'})
siblings.set_attr_for_nodes(['Monique Arellano'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=972'})
siblings.set_attr_for_nodes(['Anthony Henderson'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=973'})
siblings.set_attr_for_nodes(['Amethyst Tagle'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=974'})
siblings.set_attr_for_nodes(['Mallory Williams'], {'color': 'lightpink', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=975'})
siblings.set_attr_for_nodes(['Edward Givens'], {'color': 'lightblue', 'outline': 'bold', 'style': 'bold', 'URL': 'http://sdsu.kkytbs.net/members/profile.html?who=106'})

siblings.save_fig('siblings.svg')
